### ISSUE TITLE
ServiceNow Import fail issue "Repository authentication failed, check credentials. Make sure the user has both read and write access"

### ISSUE THREAD

**Issue by rbl69** [byukich/x_snc_aws_sns#1]
Hello,

When we are trying to import the application in ServiceNow by Studio on an ootb Orlando instance.

Printscreen :
[Import ServiceNow](https://ibb.co/DCtMYZt)

... we have an authentification failure : “Repository authentication failed, check credentials. Make sure the user has both read and write access”.

Printscreen :
[Failure](https://ibb.co/w4c9g2L)

We hadn't this issue there is one month ago. Something changed ? Is there a new authentification ?

Regards,

**Comment by byukich** [comment]
Thanks for letting me know! It looks like this is a change in behavior starting (I assume) in the Orlando release (I was able to get the same error in an Orlando, but not a New York instance). Assuming you're a ServiceNow customer, you may want to reach out to support to see if e.g. there are any settings you can change to make it work. In the short term, if you fork the project into your own account it should work fine (as then you'll have both read & write access).

**Comment by iamsaida485** [comment]
Hello,

I have fixed this issue and able to upload it to service now

**Comment by saschawildgrube** [comment]
How did you fix the issue?

**Comment by byukich** [comment]
Hey @saschawildgrube, ServiceNow changed the permissions required for app imports from github - write privileges are required beginning with the Orlando release. To resolve, just fork this repo so you can import from your own read/write account (it appears this is what @iamsaida485 did).

**Comment by saschawildgrube** [comment]
Hi @byukich. In fact GitHub must have changed something. Username/password is no longer accepted as a credential. The solution was to create an access token in GitHub and use it as the password within ServiceNow.
The repos in question in my case were my own. I have full read/write access to them.

**Comment by darshantn4** [comment]
"Repository authentication failed, check credentials. Make sure the user has both read and write access" getting this error

 
Tried below possibilities but no use.

Updated the git password and updated in the credentials in SNow didn't work

Deleted the repository and adding again even that didn't workout.

Should we need to give permission to Git account in git site. If yes, please let me know what are the steps to be followed. @byukich

**Comment by iamsaida485** [comment]
@saschawildgrube @darshantn4 

Follow below steps to fix it.
1. Fork the x_snc_aws_sns repository to your repository.
2. Create Basic Auth cred in Service Now with Git User id and Password.
3. Go to Studio give url as your fork repo url and remove .git in the url.
4. Change Branch name to Master.
5. Use Cred as the Basic Auth which was created in step2.
6. Click on Import.

**Comment by nkronline** [comment]
The user only has read access to the repo. Make sure the user has both read and write access

**Comment by fvalivand** [comment]
import application failure. the user has only read access to the repo. make sure the user has both read and write access.

**Comment by fvalivand** [comment]
this is something I got. I dont know how can I fix it?

**Comment by saschawildgrube** [comment]
Do this:
1. Go to github.com
2. Navigate to "Settings"
3. Navigate to "Developer"
4. Create a new token
5. Enter the created token as the password within the credentials used for GitHub in ServiceNow

I know, the error messages in ServiceNow are... - well - there is room for improvement :D

**Comment by davedotdev** [comment]
Room for improvement. +1. Thanks @saschawildgrube for a workable solution.

**Comment by iamsaida485** [comment]
Follow below steps to fix it.

Fork the x_snc_aws_sns repository to your repository.
Create Basic Auth cred in Service Now with Git User id and Password.
Go to Studio give url as your fork repo url and remove .git in the url.
Change Branch name to Master.
Use Cred as the Basic Auth which was created in step2.
Click on Import.

I followed above steps it worked for me

**Comment by sk-snow-developer** [comment]
1) Login to GITHub and got to User Menu -> Settings -> Developer settings -> Personal access tokens (https://github.com/settings/tokens)
Create new token entry. Make sure to save your personal access token as soon as it is displayed. You won’t be able to see it afterwards. You can use ‘Regenerate token’ in order to generate new token value. 
See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

2) ServiceNow -> Application Navigator -> Connections & Credentials -> Credentials
Create Credentials record (on ‘basic_auth_credentials’ table)
Type: Basic Auth Credentials
User Name: use your GITHub login
Password: use active token generated in the previous step

3) ServiceNow -> Application Navigator -> Studio -> Select your application which has to be linked to the GitHub repository
Menu Source Control -> Link to Source Control
Network Protocol: HTTPS
URL: https://github.com/your_github_login/your_repository_name (no ‘.git’ at the end)
Credentials: <select the created record in the previous step>
Branch: pick the name of the existing branch one or put the name of a new one, it will be created automatically
See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by thisnameissoclever** [comment]
I recently wrote a 'ServiceNow Pro Tips' article on this, which teaches you:



1. How to change which GitHub / repository your ServiceNow application in Studio

2. How to update your GitHub repo credentials in ServiceNow

3. How to generate ECDSA SSH keys and link your ServiceNow application with GitHub using SSH (including the new GitHub rule against using insecure RSA keys) - since GitHub no longer supports basic auth or RSA SSH keys

4. How to generate/link your SSH API key-pair with GitHub and ServiceNow, using your public/private keys



You can see the full article with detailed step-by-step instructions, [here:](https://snprotips.com/blog/2022/3/4/how-to-change-servicenow-applications-repositoryurl%20)

https://snprotips.com/blog/2022/3/4/how-to-change-servicenow-applications-repositoryurl

**Comment by goyalrohit2002** [comment]
> 1. Login to GITHub and got to User Menu -> Settings -> Developer settings -> Personal access tokens (https://github.com/settings/tokens)
>    Create new token entry. Make sure to save your personal access token as soon as it is displayed. You won’t be able to see it afterwards. You can use ‘Regenerate token’ in order to generate new token value.
>    See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
> 2. ServiceNow -> Application Navigator -> Connections & Credentials -> Credentials
>    Create Credentials record (on ‘basic_auth_credentials’ table)
>    Type: Basic Auth Credentials
>    User Name: use your GITHub login
>    Password: use active token generated in the previous step
> 3. ServiceNow -> Application Navigator -> Studio -> Select your application which has to be linked to the GitHub repository
>    Menu Source Control -> Link to Source Control
>    Network Protocol: HTTPS
>    URL: https://github.com/your_github_login/your_repository_name (no ‘.git’ at the end)
>    Credentials: 
>    Branch: pick the name of the existing branch one or put the name of a new one, it will be created automatically
>    See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

Thanks. It worked

**Comment by dneises22** [comment]
I also had this issue. Generating a new personal token and using that for the password in my Basic Auth credential within ServiceNow was the solution that worked for me.

**Comment by dschurch73** [comment]
There is a definite issue going on with the API to GitHub from ServiceNow using Basic Auth and a deply key for the password. I suspect it's a San Diego release issue.
Using an SSH Private Key and making sure to type the exact case sensitive branch name (main) along with using a mid-server worked for me FINALLY. I am not sure if the mid server is needed but it worked so include that in the config at your own discretion. Create a ServiceNow SSH Private key credential to use for the connection and enter your GitHub username and the SSH Private key from your existing or newly generated SSH Key. Of course the public key needs to be added to your SSH key inventory on your github account. Good luck!
![proof](https://user-images.githubusercontent.com/110921266/184372078-e9fe3d5a-ff68-4747-850a-067ba2df94c4.jpg)

**Comment by trubel** [comment]
> 

How did you fix the issue?   

I created my own empty repo and tried connecting with no luck.  Still getting a fail.

**Comment by dschurch73** [comment]
Like I mentioned above...
Use an SSH Private Key and make sure to type the exact case sensitive branch name (main) along with using a mid-server worked for me FINALLY. I am not sure if the mid server is needed but it worked so include that in the config at your own discretion. Create a ServiceNow SSH Private key credential to use for the connection and enter your GitHub username and the SSH Private key from your existing or newly generated SSH Key. Of course the public key needs to be added to your SSH keys on your GitHub account.

**Comment by MOPAC1969** [comment]
> Do this:
> 
> 1. Go to github.com
> 2. Navigate to "Settings"
> 3. Navigate to "Developer"
> 4. Create a new token
> 5. Enter the created token as the password within the credentials used for GitHub in ServiceNow
> 
> I know, the error messages in ServiceNow are... - well - there is room for improvement :D

That worked for me in connection with the Learning Module for creating "NeedIT" application. However "Developer" is "Developer settings". Thanks for your support!!

**Comment by NEEHAR-PNC** [comment]
I get this error The user only has read access to the repo. Make sure the user has both read and write access. Any suggessions?

**Comment by Tiagomacul** [comment]
Solution step by step:

The user only has read access to the repo. Make sure the user has both read and write access !!

https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0994306

**Comment by rajeshjain25** [comment]
> Do this:
> 
> 1. Go to github.com
> 2. Navigate to "Settings"
> 3. Navigate to "Developer"
> 4. Create a new token
> 5. Enter the created token as the password within the credentials used for GitHub in ServiceNow
> 
> I know, the error messages in ServiceNow are... - well - there is room for improvement :D

- Follow provided instruction, in servicenow create personal token under develop tab in settings, and use same password in basic authentication credientials.

**Comment by Sweetog** [comment]
[This](https://github.com/byukich/x_snc_aws_sns/issues/1#issuecomment-1213122793) is the correct answer >= San Diego BUT, for the SSH Private Key Credential

- do NOT use SSH-1 San Diego, strangely a SSH-1 private key will work in Utah.
- MID Servers do not matter, All MID Servers is fine
- User name does not matter

[keygen instructions](https://stackoverflow.com/questions/71500791/eclipse-git-youre-using-an-rsa-key-with-sha-1-which-is-no-longer-allowed-pl) for San Diego
`ssh-keygen -t ecdsa -b 521 -C "your_email@example.com"`

**Comment by wangyangcd** [comment]
go back to github and check when create token, if add the read and write access

**Comment by uvyavahare** [comment]
> Do this:
> 
> 1. Go to github.com
> 2. Navigate to "Settings"
> 3. Navigate to "Developer"
> 4. Create a new token
> 5. Enter the created token as the password within the credentials used for GitHub in ServiceNow
> 
> I know, the error messages in ServiceNow are... - well - there is room for improvement :D

This worked for me! Thank you!

**Comment by emdashii** [comment]
> Hi @byukich. In fact GitHub must have changed something. Username/password is no longer accepted as a credential. The solution was to create an access token in GitHub and use it as the password within ServiceNow. The repos in question in my case were my own. I have full read/write access to them.

This fixed the issue for me. I used basic auth credentials with my username and the access token as the password

**Comment by vishnuburugupalli** [comment]
While connecting to Github through servinow studio Getting this error {"error.message":"An error occurred while executing that operation. Try again, check logs, and contact support if the error persists","README.md (No such file or directory)","exception.class":"java.io.FileNotFoundException","error.code":"1000"}
