### ISSUE TITLE
Repository authentication failed, check credentials. Make sure the user has both read and write access

### ISSUE THREAD

**Issue by Eeshwar-Soma** [byukich/x_snc_aws_sns#2]
Hello,

I am trying to Integrate GitHub with ServiceNow in my personal Instance, But while I am adding GitHub to ServiceNow with using Source control I can see the error like **"**Repository authentication failed, check credentials. Make sure the user has both read and write access"****.  I can not see the login details like User name and password on the source control.
Can anyone please help me on this.
![GIT erroe1](https://user-images.githubusercontent.com/81635398/113177686-6915c380-9213-11eb-9f5c-224a36d6d631.PNG)
![Git erroe2](https://user-images.githubusercontent.com/81635398/113177705-6d41e100-9213-11eb-927a-a20c05ffabd0.PNG)

**Comment by byukich** [comment]
Hey thanks for your patience! To resolve, please fork this project so that you have both read and write ability. ServiceNow changed the expected permissions for github some time ago, so now it must be a repository you have full control of (rather than read only) in order to import into an instance.
